### PR TITLE
MessageBox abstraction

### PR DESCRIPTION
**Pull request by pmacn**
Add ShowMessage methods to IDialogFacade and as extensions

### CODE REVIEW

**Comment by pmacn** [comment]
A little uneasy by the fact that using the extensions methods here would let you use the `MessageBox.Show` sans `MessageBoxOptions` without getting the CA1300 warning. But at least it's hidden away in the Extensions namespace so that's good.

**Comment by Haacked** [comment]
Hmm, maybe we should force consumers to specify the options and remove the extensions? What do you think?

**Comment by pmacn** [comment]
I think that just including the overloads that use `MessageBoxOptions` would be fine. Then if someone knows what they're doing and they definitely don't need localization they can make their own extension methods.

**Comment by Haacked** [comment]
:thumbsup:

**Pull request merged**
