### PR TITLE
Add visual studio test runners

### PR DESCRIPTION
**Pull request by pmacn**
Installed NuGet package xunit.runner.visualstudio

### CODE REVIEW

**Comment by Haacked** [comment]
Weird, I think Fody is mistaken. NuGet Restore is enabled. I wonder if it's looking for the old school restore feature and not the modern restore.

**Comment by pmacn** [comment]
If I'm not mistaken the new one is very VS specific and doesn't work when just running msbuild

**Comment by Haacked** [comment]
Oh. Am I not using VS to buid? We should probably just shell out to `nuget restore ...` then.

**Comment by pmacn** [comment]
That would probably be the simplest possible fix since nuget.exe is already in the repo.

**Comment by Haacked** [comment]
Care to take a cut at it? I'd do it, but I drank too much Scotch and I'm past the Ballmer's peak.

**Comment by pmacn** [comment]
Sounds like a good evening :) I'm heading to bed though, one hour ahead here and gotta get my beauty sleep

**Comment by pmacn** [comment]
Hope the pain wasn't too bad today :grin:

Hadn't looked at AppVeyor in a while but it looks as if you could just add a pre build cmd. I'd gladly do it but I would guess you'd need to go in there anyway to give editing permissions (if that's even a thing, haven't used it much)

**Comment by Haacked** [comment]
Oh, I was thinking I'd just do it in our build script. But maybe we don't have one. I can't keep all my projects straight. :frowning:

**Comment by pmacn** [comment]
It has a build script but that's not what AppVeyor runs iirc :) Could just
change it to run the script however

**Pull request merged**
