### PR TITLE
Fix running tests in build script.

### PR DESCRIPTION
**Pull request by pmacn**
Update FAKE.Core
Remove download of FAKE.Core in build.cmd. Binaries were both being
checked in and downloaded on each script run so I opted for leaving them
checked in.
Update build script to use xUnit2Helper

### CODE REVIEW

**Comment by pmacn** [comment]
If we'd rather have nuget download fake each time I can change it to do that and removed the checked in binaries instead. Just took this approach as it currently wasn't downloading binaries for xunit and it was doing both for FAKE.

**Comment by pmacn** [comment]
Also had a commit after this one that added the changes you had in the other PR but figured you should just be able to rebase that once this is in and you should be set.

**Comment by pmacn** [comment]
Looks like I might have missed something AppVeyor specific, will have a look

**Comment by pmacn** [comment]
Seems unrelated. It just needs to restore packages before running msbuild. Guess adding the NuGet package restore build task would do the trick as well.

**Comment by Haacked** [comment]
selfie-0

**Pull request merged**
